### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by sy-be** [ValdikSS/aceproxy#46]
Is the project considered as abandoned as the repo title says? I'm building an HTPC now and might contribute something back if I find bugs or things to improve (if any).

**Comment by ValdikSS** [comment]
Yep, it's abandoned (by me). Ace Stream developers don't want to fix existing bugs, don't want to hear me and even banned me once. Their main investor Constantin is crazy and has no idea how the software works, yet always replying on their forums first. Hell, they even used their browser extension to replace advertisement on the websites with theirs, to get money for nothing.
I've lost interest in Ace Stream more than a year ago and don't want to support anything which uses Ace Stream anymore, including AceProxy. AFAIK, @deseven was banned by Torrent TV and @miltador deleted his account because he didn't want to hear anything about AceEngine, yet they both were an AceProxy contributors.
Sorry for that.

**Comment by Quarx2k** [comment]
It's sad. There no better alternative for aceproxy ;(

**Comment by sy-be** [comment]
It is indeed sad and too bad there's no way to fork ace stream. I was going to setup torrent-tv and I guess currently there's no better alternative than acestream + aceproxy to run on linux box, is there?

**Comment by ValdikSS** [comment]
There is a proxy from torrent tv written on Mono.

**Comment by sy-be** [comment]
I think it is outdated and does not work, I tried to launch it - and threw some exceptions, maybe it requires some specific mono version.

**Comment by sy-be** [comment]
Stupid me, it required mono-devel packages. I'll try both options but I prefer python and will suggest patches anyway for you to review :). Closing this, thanks!
